accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .views import UserList, signup, FollowerList, FollowingList, Follow

app_name = 'accounts'

urlpatterns = [
    path('user/list/', UserList.as_view(), name='user_list'),
    path('signin/', LoginView.as_view(template_name='accounts/signin.html'), name='signin'),
    path('signout/', LogoutView.as_view(template_name='accounts/signout.html'), name='signout'),
    path('signup/', signup, name='signup'),
    path('follower_list/', FollowerList.as_view(), name='follower_list'),
    path('following_list/', FollowingList.as_view(), name='following_list'),
    path('follow/<int:follow_id>/', Follow.as_view(), name='follow'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('account/', include('allauth.urls')),
    path('',include('photo.urls')),
]


# 특정 리소스를 static형태로 응답
from django.conf.urls.static import static

# 장고의 셋팅값을 불러주는 역할
from django.conf import settings

# 개발 상태일 때만 사용 -> Deploy, Live일 때는 사용하지 않는다.
# 1) 웹 서버가 해줘야 할 일
# 2) 파일 서버를 별도로 셋팅
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photo/urls.py
from django.urls import path

from .views import *

app_name = 'photo'

urlpatterns = [
    path('create/', PhotoCreate.as_view(), name='create'),
    path('update/<int:pk>/', PhotoUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', PhotoDelete.as_view(), name='delete'),
    path('detail/<int:pk>/', PhotoDetail.as_view(), name='detail'),

    path('comment/create/<int:photo_id>/', comment_create, name='comment_create'),
    path('comment/update/<int:comment_id>/', comment_update, name='comment_update'),
    path('comment/delete/<int:comment_id>/', comment_delete, name='comment_delete'),

    path('like/<int:photo_id>/', PhotoLike.as_view(), name='like'),
    path('like/', PhotoLikeList.as_view(), name='like_list'),

    path('favorite/', PhotoSaveList.as_view(), name='favorite_list'),
    path('favorite/<int:photo_id>/', PhotoSave.as_view(), name='favorite'),

    path('mylist/', PhotoMyList.as_view(), name='mylist'),
    path('',PhotoList.as_view(), name='index'),
]

accounts/models.py
from django.db import models

# Create your models here.
# 중간 모델 작성

from django.contrib.auth.models import User

class Follow(models.Model):
    # 2개 필드 - ForeignKey
    # A가 B를 팔로우 하고 있다.
    # on_delete : 연관된 객체가 삭제된다면 어떻게 할 것이냐?
    # related_name : 참조객체의 입장에서 필드명, 속성값

    # 내가 팔로우 한 사람
    me = models.ForeignKey(User, on_delete=models.CASCADE, related_name='following')

    # 나를 팔로우 한 사람
    you = models.ForeignKey(User, on_delete=models.CASCADE, related_name='follower')

    def __str__(self):
        return self.me.username+" follow "+self.you.username

accounts/forms.py
# 모델 폼을 만들려면 2가지 필요
# (제네릭 뷰 : 제네릭 뷰, 모델)
# 모델 폼 : 모델, 폼

from django.contrib.auth.models import User
from django import forms

class SignUpForm(forms.ModelForm):
    # 작성 중 비밀번호 안보이게 하기, Meta보다 우선순위가 높음
    password = forms.CharField(label='Password', widget=forms.PasswordInput) # 우선순위가 높음
    password2 = forms.CharField(label='Repeat Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        # fields 에는 해당 모델에 대해 입력받을 필드들을 나열한다.
        # 추가 필드도 포함될 수 있다. -> 필드 목록과 추가 필드가 겹치면 오버라이드 됨
        # fields 에 작성한 순서대로 출력한다.
        fields = ['username', 'password', 'password2', 'first_name', 'last_name', 'email'] # 입력 받을 내용
        # fields = '__all__' # 전부 입력 받을 때는 __all__

        # Todo : 필드의 기본 값, Placeholder 설정법, css Class 설정법, Validator 설정법, help text 설정법
        # Todo : 커스텀 필드 만드는 법

    # Repeat Password가 일치하지 않을 때
    # def clean_필드명(self):
    def clean_password2(self):
        cd = self.cleaned_data

        if cd['password'] != cd['password2']:
            raise forms.ValidationError('비밀번호가 일치하지 않습니다.')
        # 항상 필드의 값을 리턴한다.
        return cd['password2']

accounts/views.py
from django.shortcuts import render

# Create your views here.
# 유저 목록이 출력되는 뷰
# + follow 기능
# 중간 테이블을 직접 생성 - 모델

# 유저 모델 -> 유저 모델을 커스터마이징
# 확장하는 방법에 따라
# 1) 새로운 유저 모델을 만드는 방법 - 기존 유저 데이터를 유지할 수 없음
# 2) 기존 모델을 확장하는 방법 - DB 다운 타임 발 alter table - table lock

# 나를 팔로우 - 필드
# 내가 팔로우 - 필드

# 커스터마이징 불가할 경우
# 새로운 모델을 추가

# 사진 모델
# 사진을 좋아요 한 사람 - 필드
# 사진을 저장 한 사람 - 필드

"""
1. 유저 목록 or 유저 프로필에서 팔로우 버튼
1-1. 전체 유저 목록을 출력해주는 뷰 - 유저 모델에 대한 ListView
2. 팔로우 정보를 저장하는 뷰
"""

from .models import Follow

from django.views.generic.list import ListView
from django.contrib.auth.models import User


class UserList(ListView):
    model = User
    template_name = 'accounts/user_list.html'


class FollowerList(ListView):
    model = Follow
    template_name = 'accounts/follower_list.html'

    def get_queryset(self):
        user = self.request.user
        queryset = user.follower.all()
        return queryset

class FollowingList(ListView):
    model = Follow
    template_name = 'accounts/following_list.html'

    def get_queryset(self):
        user = self.request.user
        queryset = user.following.all()
        return queryset

from django.views.generic.base import View
from django.http import HttpResponseForbidden
from urllib.parse import urlparse
from django.http import HttpResponseRedirect

class Follow(View):
    def get(self, request, *args, **kwargs):

        # like를 할 정보가 있다면 진행, 없다면 중단
        if not request.user.is_authenticated:
            return HttpResponseForbidden
        else:
            if 'follow_id' in kwargs:
                follow_id = kwargs['follow_id']
                follow = Follow.objects.get(pk=follow_id)

                # 2) 누가?
                user = request.user
                if user in follow.me:
                    follow.me.remove(user)
                else:
                    follow.you.add(user)

            referer_url = request.META.get('HTTP_REFERER')
            path = urlparse(referer_url).path

            return HttpResponseRedirect(path)

# 기본에 입력받는 뷰는 CreateView 를 상속 -> 커스텀이 힘듦
# 회원가입 -> User 모델에 값을 입력받는다. -> CreateView
# 회원가입시 모델 필드 외에 추가 입력이 필요하다.
# 커스텀은 함수형 뷰가 적절
from django.contrib.auth.models import User
from .forms import SignUpForm

def signup(request):
    # class based view -> dispatch -> get, post
    if request.method == "POST":
        # form 이 채워져 있는 형태
        signup_form = SignUpForm(request.POST)

        # form validation
        if signup_form.is_valid():
            # 1. 저장하고 인스턴스 생성
            user_instance = signup_form.save(commit=False) # commit=False : DB 에는 저장 안됐으나 인스턴스는 생성
            # 2. 패스워드 암호화 -> 저장
            # form 이 가지고 있는 cleaned_data : 유효한 문자만 남긴 상태로, 처리 과정을 거친 데이터
            user_instance.set_password(signup_form.cleaned_data['password'])
            user_instance.save()

            return render(request, 'accounts/signup_complete.html', {'username':user_instance.username})
    else:
        signup_form = SignUpForm()

    return render(request, 'accounts/signup.html', {'form':signup_form})

from allauth.account.signals import user_signed_up
from allauth.socialaccount.models import SocialAccount

def naver_signup(request, user, **kwargs):
    social_user = SocialAccount.objects.filter(user=user)

    if social_user.exists():
        user.last_name = social_user[0].extra_data['name']
        user.save()


# 시그널과 해당 함수를 connect
# 시그널 연결방법
# 1. receiver
# 2. connect
user_signed_up.connect(naver_signup)

from django.http import JsonResponse

accounts/templates/accounts/follower_list.html
{% extends 'base.html' %}

{% block title %}
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-6">
        <table class="table text-center">
            <thead>
            <tr>
                <th scope="col">UserName</th>
                <th scope="col">Un/Follow</th>
            </tr>
            </thead>

            <tbody>
            {% for object in object_list %}
            <tr>
                <td>{{object.me.username}}</td>
                <td><a href="{% url 'accounts:follow' object.id %}" class="btn btn-xs btn-outline-success">Follow</a></td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

accounts/templates/accounts/following_list.html
{% extends 'base.html' %}

{% block title %}
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-6">
        <table class="table text-center">
            <thead>
            <tr>
                <th scope="col">UserName</th>
                <th scope="col">Un/Follow</th>
            </tr>
            </thead>

            <tbody>
            {% for object in object_list %}
            <tr>
                <td>{{object.you.username}}</td>
                <td><a href="" class="btn btn-xs btn-outline-success">Follow</a></td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

accounts/templates/accounts/signin.html
{% extends 'base.html' %}

{% block title %}
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-6">
        <div class="alert alert-primary">Please enter your login information.</div>
        <form action="" method="post">
            {% csrf_token %}

            {{form.as_p}}
            <input type="submit" value="Sign in" class="btn btn-outline-primary">
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

accounts/templates/accounts/signout.html
{% extends 'base.html' %}

{% block title %}
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-6">
        <div class="alert alert-primary">You successfully sign out.</div>
        <a href="{% url 'accounts:signin' %}" class="btn btn-outline-success">Sign In</a>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block title %}
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-6">
        <div class="alert alert-primary">Please enter your accounts information.</div>
        <form action="" method="post">
            {% csrf_token %}

            {{form.as_p}}
            <input type="submit" value="Sign up" class="btn btn-outline-primary">
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

accounts/templates/accounts/signup_complete.html
{% extends 'base.html' %}

{% block title %}
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-6">
        <div class="alert alert-primary">{{username}} You successfully signed up</div>

        <a href="{% url 'accounts:signin' %}" class="btn btn-outline-success">Move to Sign In</a>

    </div>
    <div class="col"></div>
</div>
{% endblock %}

accounts/templates/accounts/user_list.html
{% extends 'base.html' %}

{% block title %}
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-6">
        <table class="table text-center">
            <thead>
            <tr>
                <th scope="col">UserName</th>
                <th scope="col">Un/Follow</th>
                <th scope="col">Follower</th>
                <th scope="col">Following</th>
            </tr>
            </thead>

            <tbody>
            {% for object in object_list %}
            <tr>
                <td>{{object.username}}</td>
                <td><a href="" class="btn btn-xs btn-outline-success">Follow</a></td>
                <td>{{object.follower.all.count}}</td>
                <td>{{object.following.all.count}}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col"></div>
</div>
{% endblock %}