config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('account/', include('allauth.urls')),
    path('',include('photo.urls')),
]


# 특정 리소스를 static형태로 응답
from django.conf.urls.static import static

# 장고의 셋팅값을 불러주는 역할
from django.conf import settings

# 개발 상태일 때만 사용 -> Deploy, Live일 때는 사용하지 않는다.
# 1) 웹 서버가 해줘야 할 일
# 2) 파일 서버를 별도로 셋팅
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photo/urls.py
from django.urls import path

from .views import *

app_name = 'photo'

urlpatterns = [
    path('create/', PhotoCreate.as_view(), name='create'),
    path('update/<int:pk>/', PhotoUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', PhotoDelete.as_view(), name='delete'),
    path('detail/<int:pk>/', PhotoDetail.as_view(), name='detail'),

    path('comment/create/<int:photo_id>/', comment_create, name='comment_create'),
    path('comment/update/<int:comment_id>/', comment_update, name='comment_update'),
    path('comment/delete/<int:comment_id>/', comment_delete, name='comment_delete'),

    path('like/<int:photo_id>/', PhotoLike.as_view(), name='like'),
    path('like/', PhotoLikeList.as_view(), name='like_list'),

    path('favorite/', PhotoSaveList.as_view(), name='favorite_list'),
    path('favorite/<int:photo_id>/', PhotoSave.as_view(), name='favorite'),

    path('mylist/', PhotoMyList.as_view(), name='mylist'),
    path('',PhotoList.as_view(), name='index'),
]

photo/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model

# User 모델은 확장 가능
# settings.AUTH_USER_MODEL

# from django.contrib.auth import get_user_model
# author = models.ForeignKey(get_user_model)

from django.urls import reverse
# url pattern 이름을 가지고 주소를 만들어주는 함수

# Create your models here.
# models.Model : ORM 관련 기능을 다 가지고 있다.
class Photo(models.Model):
    # ForeignKey(연결되는 모델, 삭제 시 동작, 연관 이름)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='photos')
    # CASCADE : 연속해서 지운다. -> 탈퇴하면 사진도 지움
    # PROTECT : 사진이 남아있으면 탈퇴 불가 -> 탈퇴 프로세스에 사진을 삭제하고 탈퇴시킴
    # 특정값으로 셋팅

    # 글 삭제 : DB 로우, 레코드를 삭제 -> 메모리에 남아 있는 사진 삭제

    # related_name 으로 연관 데이터를 얻을 수 없다면 쿼리를 별도로 진행해야 한다. -> 내 프로필 페이지

    text = models.TextField(blank=True)
    image = models.ImageField(upload_to='timeline_photo/%Y/%m/%d')
    # upload_to : 함수를 사용해서 폴더를 동적으로 설정할 수 있다.
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    # like 정보 저장
    like = models.ManyToManyField(User, related_name='like_post', blank=True)

    # save 정보 저장
    favorite = models.ManyToManyField(User, related_name='save_post', blank=True)

    class Meta:
        ordering = ['-created']

    def get_absolute_url(self):
        # detail/<int:pk>/
        return reverse('photo:detail', args=[self.id])


    # # save 를 실행하고 나면 DB 에 레코드 생성
    # # save 하기 전에 수행할 동작
    # # save 하고 나서 수행할 동작
    # def save(self, force_insert=False, force_update=False, using=None,
    #          update_fields=None):
    #     # before
    #     super(Photo,self).save()
    #     # after
    #
    # # delete 를 실행하고 나면 DB 에서 레코드 제거
    # # delete 하기 전에 수행할 동작
    # # delete 하고 나서 수행할 동작
    # def delete(self, using=None, keep_parents=False):
    #     # before
    #     super(Photo,self).delete()
    #     # after

class Comment(models.Model):
    # TODO : 댓글 남기기를 위해서 form이 필요
    # TODO : Document의 뷰에서 처리
    photo = models.ForeignKey(Photo, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True, blank=True, related_name='comments')
    text = models.CharField(max_length=400)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return (self.author.username if self.author else "무명") + "의 댓글"

    def get_absolute_url(self):
        return reverse('photo:detail', args=[self.id])

photo/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['text'].label = "Comment"
        self.fields['text'].widget = forms.TextInput()
        self.fields['text'].widget.attrs = {'class': "form-control", 'placeholder': "댓글을 입력하세요"}

photo/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin
# 뷰를 실행하기 전에 특정한 로직을 추가로 실행하고 싶을 때 사용
# 로그인 여부, csrf 체크를 수행할것인지?
# 믹스인 : 클래스형 뷰
# 데코레이터 : 함수형 뷰

from .models import *

class PhotoList(LoginRequiredMixin, ListView):
    model = Photo
    template_name = 'photo/photo_list.html'
    # paginate_by = 2


class PhotoMyList(LoginRequiredMixin, ListView):
    model = Photo
    template_name = 'photo/photo_list.html'

    def get_queryset(self):
        user = self.request.user
        queryset = user.photos.all()
        return queryset


class PhotoLikeList(LoginRequiredMixin, ListView):
    model = Photo
    template_name = 'photo/photo_list.html'

    def get_queryset(self):
        # 로그인 한 유저가 좋아요를 클릭한 글을 찾아서 반환
        user = self.request.user
        queryset = user.like_post.all()
        return queryset


class PhotoSaveList(LoginRequiredMixin, ListView):
    model = Photo
    template_name = 'photo/photo_list.html'

    def get_queryset(self):
        # 로그인 한 유저가 저장을 클릭한 글을 찾아서 반환
        user = self.request.user
        queryset = user.save_post.all()
        return queryset

class PhotoCreate(LoginRequiredMixin, CreateView):
    model = Photo
    fields = ['text', 'image']
    template_name = 'photo/photo_create.html'
    success_url = '/'

    def form_valid(self, form):
        # 입력된 자료가 올바른지 채크
        form.instance.author_id = self.request.user.id
        if form.is_valid():
            # 올바르다면
            # form : 모델 폼
            form.instance.save()
            return redirect('/')
        else:
            # 올바르지 않다면
            return self.render_to_response({'form':form})

class PhotoUpdate(LoginRequiredMixin, UpdateView):
    model = Photo
    fields = ['text', 'image']
    template_name = 'photo/photo_update.html'

    def dispatch(self, request, *args, **kwargs):
        # 사용자가 접속했을 때 get인지, post인지 등을 결정하고 분기하는 부분

        object = self.get_object()

        if object.author != request.user:
            messages.warning(request, "수정할 권한이 없습니다.")
            return HttpResponseRedirect(object.get_absolute_url())
        else:
            return super(PhotoUpdate, self).dispatch(request, *args, **kwargs)


from django.http import HttpResponseRedirect
from django.contrib import messages

class PhotoDelete(LoginRequiredMixin, DeleteView):
    model = Photo
    template_name = 'photo/photo_delete.html'
    success_url = '/'

    # Life Cycle - ios, android, vue, react, django, fails
    # Framework 는 Life Cycle이 존재 : 어떤 순서로 구동이 되느냐?
    # URLConf -> View -> Model 순서
    # 어떤 뷰를 구동할 때 그 안에서 동작하는 순서
    def dispatch(self, request, *args, **kwargs):
        # 사용자가 접속했을 때 get인지, post인지 등을 결정하고 분기하는 부분

        object = self.get_object()

        if object.author != request.user:
            # 1) 삭제 페이지에서 권한이 없다 출력
            # 2) 디테일 페이지로 다시 돌아가서 삭제 실패 출력
            messages.warning(request, "삭제할 권한이 없습니다.")
            return HttpResponseRedirect(object.get_absolute_url())
        else:
            return super(PhotoDelete, self).dispatch(request, *args, **kwargs)

    # # 로직을 수행하고, 템플릿을 랜더링 한다.
    # def get(self, request, *args, **kwargs):
    #     pass
    #
    # def post(self, request, *args, **kwargs):
    #     pass


    # def det_object(self, queryset=None):
    #     # 해당 쿼리셋을 이용해서 현재 페이지에 필요한 object를 인스턴스화 한다.
    #     pass
    #
    # def get_queryset(self):
    #     # 어떻게 데이터를 가져올 것이냐?
    #     pass

class PhotoDetail(LoginRequiredMixin, DetailView):
    model = Photo
    template_name = 'photo/photo_detail.html'

    def photo_detail(request, photo_id):
        photo = Photo.objects.get(pk=photo_id)
        comment_form = CommentForm()
        comments = photo.comments.all()
        return render(request,
                      {'object': photo, 'comments': comments, 'comment_form': comment_form})


from django.views.generic.base import View
from django.http import HttpResponseForbidden
from urllib.parse import urlparse

class PhotoLike(View):
    def get(self, request, *args, **kwargs):

        # like를 할 정보가 있다면 진행, 없다면 중단
        if not request.user.is_authenticated:
            return HttpResponseForbidden
        else:
            # 1) 어떤 포스팅에?
            # 1-1) url : www.naver.com/blog/like/?photo_id=1
            # request.GET.get('photo_id')

            # 1-2) url : www.naver.com/blog/like/1
            # path('blog/like/<int:photo_id>/')
            # kwargs['photo_id']
            if 'photo_id' in kwargs:
                photo_id = kwargs['photo_id']
                photo = Photo.objects.get(pk=photo_id)

                # 2) 누가?
                user = request.user
                if user in photo.like.all():
                    photo.like.remove(user)
                else:
                    photo.like.add(user)

            referer_url = request.META.get('HTTP_REFERER')
            path = urlparse(referer_url).path

            return HttpResponseRedirect(path)


class PhotoSave(View):
    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden
        else:
            if 'photo_id' in kwargs:
                photo_id = kwargs['photo_id']
                photo = Photo.objects.get(pk=photo_id)
                user = request.user

                if user in photo.favorite.all():
                    photo.favorite.remove(user)
                else:
                    photo.favorite.add(user)

            referer_url = request.META.get('HTTP_REFERER')
            path = urlparse(referer_url).path

            return HttpResponseRedirect(path)

# signal
# 1. 어떤 시그널이 발생했을 때 반응할 것인지?
# 2. 해당 시그널이 발생한 여부 확인

from django.db.models.signals import post_delete
from django.dispatch import receiver

import boto3
from django.conf import settings


@receiver(post_delete, sender=Photo) # 어떤 시그널이 발생헀는지, 누가 발생시켰는지
def post_delete(sender, instance, **kwargs):
    storage = instance.image.storage

    if storage.exists(str(instance.image)):
        storage.delete(str(instance.image))

    # session = boto3.Session(
    #     aws_access_key_id=settings.AWS_ACCESS_KEY_ID,
    #     aws_secret_access_key=settings.AWS_SECRET_ACCESS_KEY,
    #     region_name=settings.AWS_REGION,
    # )
    #
    # s3 = session.resource('s3')
    #
    # # s3 Object : s3 에 업로드 된 파일 객체를 얻어도는 클래스
    # # arg1 : 버킷네임
    # # arg2 : 파일경로 - key
    # image = s3.Object(settings.AWS_STORAGE_BUCKET_NAME, "media/"+str(instance.image)) # 버킷 네임, 파일경로
    # image.delete();;;

from .forms import CommentForm
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.shortcuts import render, get_object_or_404

# ajax사용해서 댓글 달기
def comment_create(request, photo_id):
    # ajax 기능에 의해 호출된 것인지 구분하기 위한 값
    is_ajax = request.POST.get('is_ajax')

    photo = get_object_or_404(Photo, pk=photo_id)
    comment_form = CommentForm(request.POST)
    comment_form.instance.author_id = request.user.id
    comment_form.instance.photo_id = photo_id
    if comment_form.is_valid():
        comment = comment_form.save()

    # 만약 ajax 가 호출되었다면 redirection 없이 Json 형태로 응답
    if is_ajax:
        # 데이터 만들어서 던져주기
        html = render_to_string('photo/comment/comment_single.html', {'comment':comment})
        return JsonResponse({'html':html})
    return redirect(photo)

def comment_update(request, comment_id):
    is_ajax, data = (request.GET.get('is_ajax'), request.GET) if 'is_ajax' in request.GET else (request.POST.get('is_ajax', False), request.POST)

    comment = get_object_or_404(Comment, pk=comment_id)
    photo = get_object_or_404(Photo, pk=comment.photo.id)
    # user.is_staff
    # user.is_superuser
    if request.user != comment.author:
        messages.warning(request, "권한 없음")
        return redirect(photo)

    if is_ajax:
        form = CommentForm(data, instance=comment)
        if form.is_valid():
            form.save()
            return JsonResponse({"works": True})

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            form.save()
            return redirect(photo)
    else:
        form = CommentForm(instance=comment)
    return render(request, 'photo/comment/comment_update.html', {'form': form})


def comment_delete(request, comment_id):
    is_ajax = request.GET.get('is_ajax') if 'is_ajax' in request.GET else request.POST.get('is_ajax',False)
    comment = get_object_or_404(Comment, pk=comment_id)
    photo = get_object_or_404(Photo, pk=comment.photo.id)

    if request.user != comment.author and not request.user.is_staff and request.user != photo.author:
        messages.warning(request, "권한 없음")
        return redirect(photo)

    if is_ajax:
        comment.delete()
        return JsonResponse({"works":True})

    if request.method == "POST":
        comment.delete()
        return redirect(photo)
    else:
        return render(request, 'photo/comment/comment_delete.html', {'object': comment})

photo/templates/photo/comment_list.html
<div class="row">
    <div class="col"></div>
    <div class="col-6">
        <table class="table table-striped" id="comment_list">
            <thead>
            <tr>
                <th colspan="3" class="align-left">댓글목록</th>
            </tr>
            </thead>

            <tbody>
            {% for comment in comments %}
                {% include 'photo/comment/comment_single.html' %}
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col"></div>
</div>

photo/templates/photo/photo_create.html
{% extends 'base.html' %}

{% block title %}
Photo Upload
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-6">

        <div class="alert alert-info" role="alert">Please enter your photo information</div>

        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            {{form.as_p}}
            <input type="submit" value="Upload">
        </form>

    </div>
    <div class="col"></div>
</div>
{% endblock %}

photo/templates/photo/photo_delete.html
{% extends 'base.html' %}

{% block title %}
Photo Delete
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-8">

        <div class="alert alert-info" role="alert">
            Do you want to delete?
        </div>

        <form action="" method="post">
            {% csrf_token %}
            <input type="submit" value="Delete OK">
        </form>

    </div>
    <div class="col"></div>
</div>
{% endblock %}

photo/templates/photo/photo_detail.html
{% extends 'base.html' %}

{% block title %}
Photo Detail
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-6">
        <div class="card" style="margin-top:2em;">
            <div class="card-header">
                {{object.author.username}}
            </div>

            <img src="{{object.image.url}}" class="card-img-top">

            {% if object.text %}
            <div class="card-body">
                <p class="card-text">{{object.text}}</p>
            </div>
            {% endif %}

            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <a href="{% url 'photo:like' object.id %}"
                       class="float-left btn-like {%if user in object.like.all%}active{%endif%}">Like</a>
                    {% if object.like.all.count %}
                    <span class="float-left">{{object.like.all.count}}</span>
                    {% endif %}

                    <a href="{% url 'photo:favorite' object.id %}"
                       class="float-right btn-save {%if user in object.favorite.all%}active{%endif%}">Save</a>
                </li>

                <li class="list-group-item">
                    <a href="{% url 'photo:update' object.id %}" class="card-link">수정</a>
                    <a href="{% url 'photo:delete' object.id %}" class="card-link">삭제</a>
                </li>

                <form action="{% url 'photo:comment_create' object.id %}" method="post" id="comment_form">
                    {% csrf_token %}
                    <input type="hidden" value="" name="is_ajax">
                    {{comment_form.as_p}}
                    <input type="submit" value="comment" class="btn btn-outline-secondary float-right">
                </form>

                <div id="docs_comment_list_area">
                    {% include 'photo/comment_list.html' %}
                </div>
            </ul>

            <div class="card-body">
                {# load xxx -> 해당 태그 기능을 지금부터 사용하겠다 라는 뜻 #}
                {# {% load disqus_tags %} #}
                {# {% disqus_show_comments %} #}
            </div>
        </div>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

photo/templates/photo/photo_list.html
{% extends 'base.html' %}

{% block title %}
Photo List
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-6">

        {% for object in object_list %}
        <div class="card" style="margin-top:2em;">
            <div class="card-header">
                {{object.author.username}}
            </div>

            <img src="{{object.image.url}}" class="card-img-top">

            {% if object.text %}
            <div class="card-body">
                <p class="card-text">{{object.text}}</p>
            </div>
            {% endif %}

            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <a href="{% url 'photo:like' object.id %}"
                       class="float-left btn-like {%if user in object.like.all%}active{%endif%}">Like</a>
                    {% if object.like.all.count %}
                    <span class="float-left btn btn-outline-danger">{{object.like.all.count}}</span>
                    {% endif %}

                    <a href="{% url 'photo:favorite' object.id %}"
                       class="float-right btn-save {%if user in object.favorite.all%}active{%endif%}">Save</a>
                </li>
            </ul>

            <div class="card-body">
                <a href="{{object.get_absolute_url}}" class="card-link">댓글 달기</a>
            </div>
        </div>
        {% endfor %}

    </div>
    <div class="col"></div>
</div>

{% endblock %}

photo/templates/photo/photo_update.html
{% extends 'base.html' %}

{% block title %}
Photo Update
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-6">

        <div class="alert alert-info" role="alert">Please enter your photo information</div>

        <form action="" method="post">
            {% csrf_token %}

            {{form.as_p}}
            <input type="submit" value="Update">
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}